# GoReleaser configuration for weatherornot
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: weatherornot
    main: ./cmd/weatherornot/
    binary: weatherornot
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: 386
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: weatherornot
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - weatherornot
    rlcp: true
    files:
      - README.md
      - LICENSE
      - QUICKSTART.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'README'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: james-see
    name: weatherornot
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

